# Generated by Django 5.1.7 on 2025-04-05 05:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contactus',
            name='subject',
        ),
        migrations.AddField(
            model_name='contactus',
            name='phone',
            field=models.CharField(default='0000000000', max_length=20),
        ),
    ]
