# Generated by Django 5.1.7 on 2025-04-05 07:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_remove_contactus_subject_contactus_phone'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContactUs1',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('phone', models.CharField(default='0000000000', max_length=20)),
                ('email', models.EmailField(max_length=255)),
                ('message', models.TextField()),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.DeleteModel(
            name='ContactUs',
        ),
    ]
